//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVIDIASurroundToggle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NVIDIASurroundToggle.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string CommandLineOptions_Help {
            get {
                return ResourceManager.GetString("CommandLineOptions_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Soroush Falahati v{0}.
        /// </summary>
        internal static string FrmOptions_By_Soroush_Falahati_v_0_ {
            get {
                return ResourceManager.GetString("FrmOptions_By_Soroush_Falahati_v_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I believe that I have an idea about how you expect your surround setup to be. If you think that I am wrong, click here and I will ask you about it the next time you tried to enable the surround mode..
        /// </summary>
        internal static string FrmOptions_I_believe_that_I_have_an_idea_about_how_you_expect_your_surround_setup_to_be__If_you_think_that_I_am_wrong__click_here_and_I_will_ask_you_about_it_the_next_time_you_tried_to_enable_the_surround_mode_ {
            get {
                return ResourceManager.GetString("FrmOptions_I_believe_that_I_have_an_idea_about_how_you_expect_your_surround_setup" +
                        "_to_be__If_you_think_that_I_am_wrong__click_here_and_I_will_ask_you_about_it_the" +
                        "_next_time_you_tried_to_enable_the_surround_mode_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know anything about your monitor arrangement in extended mode. Next time, I will take a copy of your settings before changing to surround mode..
        /// </summary>
        internal static string FrmOptions_I_don_t_know_anything_about_your_monitor_arrangement_in_extended_mode__Next_time__I_will_take_a_copy_of_your_settings_before_changing_to_surround_mode_ {
            get {
                return ResourceManager.GetString("FrmOptions_I_don_t_know_anything_about_your_monitor_arrangement_in_extended_mode_" +
                        "_Next_time__I_will_take_a_copy_of_your_settings_before_changing_to_surround_mode" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have no idea about your surround settings. I will ask you about it the next time you tried to enable the surround mode..
        /// </summary>
        internal static string FrmOptions_I_have_no_idea_about_your_surround_settings__I_will_ask_you_about_it_the_next_time_you_tried_to_enable_the_surround_mode_ {
            get {
                return ResourceManager.GetString("FrmOptions_I_have_no_idea_about_your_surround_settings__I_will_ask_you_about_it_t" +
                        "he_next_time_you_tried_to_enable_the_surround_mode_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I took a copy of your settings last time you was in extended mode. So I may have an idea about your desired configuration. Click here to remove this data and to ask you again later to reorganize your setup..
        /// </summary>
        internal static string FrmOptions_I_took_a_copy_of_your_settings_last_time_you_was_in_extended_mode__So_I_may_have_an_idea_about_your_desired_configuration__Click_here_to_remove_this_data_and_to_ask_you_again_later_to_reorganize_your_setup_ {
            get {
                return ResourceManager.GetString("FrmOptions_I_took_a_copy_of_your_settings_last_time_you_was_in_extended_mode__So_" +
                        "I_may_have_an_idea_about_your_desired_configuration__Click_here_to_remove_this_d" +
                        "ata_and_to_ask_you_again_later_to_reorganize_your_setup_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I tried to solve the problems, you happy now?.
        /// </summary>
        internal static string FrmOptions_I_tried_to_solve_the_problems__you_happy_now_ {
            get {
                return ResourceManager.GetString("FrmOptions_I_tried_to_solve_the_problems__you_happy_now_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string FrmOptions_Options {
            get {
                return ResourceManager.GetString("FrmOptions_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes, and especially when I get confused, I may do things that I did not intended to do. Like messing with your taskbar and NVIDIA control panel. If something like that happened to you, click here and I do my best to make it right..
        /// </summary>
        internal static string FrmOptions_Sometimes__and_especially_when_I_get_confused__I_may_do_things_that_I_did_not_intended_to_do__Like_messing_with_your_taskbar_and_NVIDIA_control_panel__If_something_like_that_happened_to_you__click_here_and_I_do_my_best_to_make_it_right_ {
            get {
                return ResourceManager.GetString("FrmOptions_Sometimes__and_especially_when_I_get_confused__I_may_do_things_that_I_" +
                        "did_not_intended_to_do__Like_messing_with_your_taskbar_and_NVIDIA_control_panel_" +
                        "_If_something_like_that_happened_to_you__click_here_and_I_do_my_best_to_make_it_" +
                        "right_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string FrmSplash__Options {
            get {
                return ResourceManager.GetString("FrmSplash__Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string FrmSplash__Tools {
            get {
                return ResourceManager.GetString("FrmSplash__Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed, Closing ....
        /// </summary>
        internal static string FrmSplash_Failed__Closing____ {
            get {
                return ResourceManager.GetString("FrmSplash_Failed__Closing____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait ....
        /// </summary>
        internal static string FrmSplash_Please_wait____ {
            get {
                return ResourceManager.GetString("FrmSplash_Please_wait____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting in {0} seconds ....
        /// </summary>
        internal static string FrmSplash_Starting_in__0__seconds____ {
            get {
                return ResourceManager.GetString("FrmSplash_Starting_in__0__seconds____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active splash screen..
        /// </summary>
        internal static string FrmSplash_There_is_no_active_splash_screen_ {
            get {
                return ResourceManager.GetString("FrmSplash_There_is_no_active_splash_screen_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While I am working, do not play with mouse and keyboard. This is a serious job..
        /// </summary>
        internal static string FrmSplash_While_I_am_working__do_not_play_with_mouse_and_keyboard__This_is_a_serious_job_ {
            get {
                return ResourceManager.GetString("FrmSplash_While_I_am_working__do_not_play_with_mouse_and_keyboard__This_is_a_seri" +
                        "ous_job_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Select.
        /// </summary>
        internal static string FrmTools_App_Select {
            get {
                return ResourceManager.GetString("FrmTools_App_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad file selected. Please select an executable file..
        /// </summary>
        internal static string FrmTools_Bad_file_selected__Please_select_an_executable_file_ {
            get {
                return ResourceManager.GetString("FrmTools_Bad_file_selected__Please_select_an_executable_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the display mode to extended.
        /// </summary>
        internal static string FrmTools_Changes_the_display_mode_to_extended {
            get {
                return ResourceManager.GetString("FrmTools_Changes_the_display_mode_to_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the display mode to surround.
        /// </summary>
        internal static string FrmTools_Changes_the_display_mode_to_surround {
            get {
                return ResourceManager.GetString("FrmTools_Changes_the_display_mode_to_surround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shortcut: App Control.
        /// </summary>
        internal static string FrmTools_Create_Shortcut__App_Control {
            get {
                return ResourceManager.GetString("FrmTools_Create_Shortcut__App_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shortcut: Commands.
        /// </summary>
        internal static string FrmTools_Create_Shortcut__Commands {
            get {
                return ResourceManager.GetString("FrmTools_Create_Shortcut__Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Mode.
        /// </summary>
        internal static string FrmTools_Extended_Mode {
            get {
                return ResourceManager.GetString("FrmTools_Extended_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the shortcut. Unexpected exception occurred..
        /// </summary>
        internal static string FrmTools_Failed_to_create_the_shortcut__Unexpected_exception_occurred_ {
            get {
                return ResourceManager.GetString("FrmTools_Failed_to_create_the_shortcut__Unexpected_exception_occurred_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0} in extended mode..
        /// </summary>
        internal static string FrmTools_Open__0__in_extended_mode_ {
            get {
                return ResourceManager.GetString("FrmTools_Open__0__in_extended_mode_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0} in surround mode..
        /// </summary>
        internal static string FrmTools_Open__0__in_surround_mode_ {
            get {
                return ResourceManager.GetString("FrmTools_Open__0__in_surround_mode_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Options.
        /// </summary>
        internal static string FrmTools_Open_Options {
            get {
                return ResourceManager.GetString("FrmTools_Open_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tools.
        /// </summary>
        internal static string FrmTools_Open_Tools {
            get {
                return ResourceManager.GetString("FrmTools_Open_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the program&apos;s configuration screen..
        /// </summary>
        internal static string FrmTools_Opens_the_program_s_configuration_screen_ {
            get {
                return ResourceManager.GetString("FrmTools_Opens_the_program_s_configuration_screen_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the program&apos;s tools screen..
        /// </summary>
        internal static string FrmTools_Opens_the_program_s_tools_screen_ {
            get {
                return ResourceManager.GetString("FrmTools_Opens_the_program_s_tools_screen_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Shortcut.
        /// </summary>
        internal static string FrmTools_Place_Shortcut {
            get {
                return ResourceManager.GetString("FrmTools_Place_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an application&apos;s executable file.
        /// </summary>
        internal static string FrmTools_Select_an_application_s_executable_file {
            get {
                return ResourceManager.GetString("FrmTools_Select_an_application_s_executable_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        internal static string FrmTools_Shortcut {
            get {
                return ResourceManager.GetString("FrmTools_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut created successfully..
        /// </summary>
        internal static string FrmTools_Shortcut_created_successfully_ {
            get {
                return ResourceManager.GetString("FrmTools_Shortcut_created_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround Mode.
        /// </summary>
        internal static string FrmTools_Surround_Mode {
            get {
                return ResourceManager.GetString("FrmTools_Surround_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string FrmTools_Timeout {
            get {
                return ResourceManager.GetString("FrmTools_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string FrmTools_Toggle {
            get {
                return ResourceManager.GetString("FrmTools_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the display mode between surround and extended.
        /// </summary>
        internal static string FrmTools_Toggles_the_display_mode_between_surround_and_extended {
            get {
                return ResourceManager.GetString("FrmTools_Toggles_the_display_mode_between_surround_and_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string FrmTools_Tools {
            get {
                return ResourceManager.GetString("FrmTools_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Process.
        /// </summary>
        internal static string FrmTools_Waiting_Process {
            get {
                return ResourceManager.GetString("FrmTools_Waiting_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Arguments.
        /// </summary>
        internal static string FrmTools_With_Arguments {
            get {
                return ResourceManager.GetString("FrmTools_With_Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of this program is in working state, please try again later..
        /// </summary>
        internal static string Program_Another_instance_of_this_program_is_in_working_state__please_try_again_later_ {
            get {
                return ResourceManager.GetString("Program_Another_instance_of_this_program_is_in_working_state__please_try_again_la" +
                        "ter_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Action Specified.
        /// </summary>
        internal static string Program_Bad_Action_Specified {
            get {
                return ResourceManager.GetString("Program_Bad_Action_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Filename Specified.
        /// </summary>
        internal static string Program_Bad_Filename_Specified {
            get {
                return ResourceManager.GetString("Program_Bad_Filename_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open a named pipe for IPC..
        /// </summary>
        internal static string Program_Can_not_open_a_named_pipe_for_IPC_ {
            get {
                return ResourceManager.GetString("Program_Can_not_open_a_named_pipe_for_IPC_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string Program_Fatal_Error {
            get {
                return ResourceManager.GetString("Program_Fatal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error: 
        /// {0}.
        /// </summary>
        internal static string Program_Fatal_Error__ {
            get {
                return ResourceManager.GetString("Program_Fatal Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t start a process in extended mode when you have another process in surround mode. Close the other program and try again..
        /// </summary>
        internal static string Program_You_can_t_start_a_process_in_extended_mode_when_you_have_another_process_in_surround_mode__Close_the_other_program_and_try_again_ {
            get {
                return ResourceManager.GetString("Program_You_can_t_start_a_process_in_extended_mode_when_you_have_another_process_" +
                        "in_surround_mode__Close_the_other_program_and_try_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t start a process in surround mode when you have another process in extended mode. Close the other program and try again..
        /// </summary>
        internal static string Program_You_can_t_start_a_process_in_surround_mode_when_you_have_another_process_in_extended_mode__Close_the_other_program_and_try_again_ {
            get {
                return ResourceManager.GetString("Program_You_can_t_start_a_process_in_surround_mode_when_you_have_another_process_" +
                        "in_extended_mode__Close_the_other_program_and_try_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement panel is not accessible from our side, can&apos;t save your settings..
        /// </summary>
        internal static string Surround_Arrangement_panel_is_not_accessible_from_our_side__can_t_save_your_settings_ {
            get {
                return ResourceManager.GetString("Surround_Arrangement_panel_is_not_accessible_from_our_side__can_t_save_your_setti" +
                        "ngs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the surround settings..
        /// </summary>
        internal static string Surround_Can_t_find_the_surround_settings_ {
            get {
                return ResourceManager.GetString("Surround_Can_t_find_the_surround_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change the surround settings..
        /// </summary>
        internal static string Surround_Failed_to_change_the_surround_settings_ {
            get {
                return ResourceManager.GetString("Surround_Failed_to_change_the_surround_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVIDIA Control Panel is absent on this system..
        /// </summary>
        internal static string Surround_NVIDIA_Control_Panel_is_absent_on_this_system_ {
            get {
                return ResourceManager.GetString("Surround_NVIDIA_Control_Panel_is_absent_on_this_system_", resourceCulture);
            }
        }
    }
}
